# frozen_string_literal: true

# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'workless_revived'
  s.version = '2.3.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 1.3.6') if s.respond_to? :required_rubygems_version=
  s.authors = ['davidakachaos']
  s.date = '2017-10-11'
  s.description = 'Extension to Delayed Job to enable workers to scale up when needed'
  s.email = 'davidakachaos@gmail.com'

  s.files = Dir.glob('{rails,lib}/**/*') + %w(LICENSE README.md )

  s.homepage = 'http://github.com/davidakachaos/workless_revived'
  s.require_paths = ['lib']
  s.summary = 'Use delayed job workers only when theyre needed on Heroku'

  s.add_runtime_dependency('workless', ['>= 2.2.0'])

  s.post_install_message = %q{
Workless Revived is no longer needed! Workless has returned!
See: https://github.com/lostboy/workless for the latest version!
This version will be the LAST VERSION!
}
end
